name: musser
favicon: null
layout_spectrum: 0.43194267665967345
typography_spectrum: 0.9454990159720182
title: the sad meanderings of an over-the-hill creative type
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.375
  lightness: 0.875
  saturation: 0.625
  rhythmicContrast: 0.8281919616274536
purpose: []
